name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SERVICE_DOMAIN: ${{ secrets.SERVICE_DOMAIN }}
      API_KEY: ${{ secrets.API_KEY }}
      FIREBASE_CLI_EXPERIMENTS: webframeworks

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Install firebase-tools
        run: npm install --save-dev firebase-tools

      - name: Set up Google credentials
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $HOME/gcloud-key.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud-key.json

      - name: Deploy to Firebase
        run: npx firebase deploy --only hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud-key.json
